---

- name: POSTGRESQL DEBIAN | Add repository key
  apt_key:
    url: "{{ postgres_apt_key }}"
    state: present

- name: POSTGRESQL DEBIAN | Add repository
  apt_repository:
    repo: "{{ postgres_apt_url }}"
    state: present

- name: POSTGRESQL DEBIAN | Installation
  package:
    name: "postgresql-{{ postgres_version }}"
    state: present
    update_cache: yes
