---

- name: POSTGRESQL INIT | Manage environment
  template:
    src: etc/profile.d/postgres.sh.j2
    dest: /etc/profile.d/postgres.sh
    owner: root
    group: root
    mode: 0644
  notify: restart postgresql

- name: POSTGRESQL INIT | Manage data directory
  file:
    path: "{{ postgres_data_dir }}"
    owner: "{{ postgres_user }}"
    group: "{{ postgres_group }}"
    state: directory
    mode: 0700

- name: POSTGRESQL INIT | Check if Postgres is initialized
  stat:
    path: "{{ postgres_data_dir }}/PG_VERSION"
  register: pgdata_dir_version

- name: POSTGRESQL INIT | Initialized the default databases
  become: true
  become_user: "{{ postgres_user }}"
  command: "{{ postgres_bin_dir }}/{{ postgres_initdb_command }}"
  environment:
    PGDATA: "{{ postgres_data_dir }}"
  when: not pgdata_dir_version.stat.exists
