---

- name: POSTGRESQL | Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: POSTGRESQL | Manage Debian environment
  import_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- name: POSTGRESQL | Manage RedHat environment
  import_tasks: redhat.yml
  when: ansible_os_family == 'RedHat'

- name: POSTGRESQL | Initialize default databases
  import_tasks: init.yml

- name: POSTGRESQL | Configuration
  import_tasks: configure.yml
