---

- name: restart postgresql
  systemd:
    name: "{{ postgres_bin }}"
    state: restarted
    enabled: true

- name: reload postgresql
  systemd:
    name: "{{ postgres_bin }}"
    state: reloaded
